### PR TITLE
added validation check to cluster commands in bug fix #39

### LINKED ISSUE #39: When project is deleted in OpenShift it remains listed in the extension
#### What did you do?

After activating the extension I deleted the project/namespace I was checked into on OpenShift

#### What did you expect to see?

An indication that my current workspace is no longer valid

#### What did you see instead? Under which circumstances?

The Operator panel commands expectedly fail. Refreshing the OpenShift Cluster Info panel does nothing to indicate the project no longer exists or change it.

#### Possible Solution

When a project is deleted in OpenShift it remains listed in the extension because the user's kube config still has it in listed under current context. When accessing their config we can do a simple check to see if the project is valid and warn the user if not.

For example, the following check can be placed in `kubernetesContext.ts`:
`if (currentContextObj.namespace is not in k8s.getNamespaceList()) { warn user project may have been deleted and should be updated }`

### PR DESCRIPTION
**Pull request by yemi-kelani**
Namespace validation with warnings cannot occur during the creation of `kubernetesObj` or `kubernetesContext`. See bug #39 for more info. It has to come before or after. I put a validation step before, and if the project doesn't exist it shows a warning message and generates the project dropdown for them to change projects.

### CODE REVIEW

File: src/kubernetes/kubernetes.ts [hunk 1]
```diff
@@ -480,4 +481,36 @@ export class KubernetesObj extends KubernetesContext {
...
+                return true;
+            } else {
+                vscode.window.showWarningMessage(`Project "${this.namespace}" does not exist on your current cluster. Please update your project`);
+
+                const projectSelection = await util.generateProjectDropDown(namespaceList);
+                if (projectSelection) {
+                    try {
+                        const ocCmd = new OcCommand();
+                        const _ = await ocCmd.runOcProjectCommand(projectSelection);
+                        vscode.window.showInformationMessage("Successfully updating Project on OpenShift cluster");
```
Comment (freemanlatrell) [inline src/kubernetes/kubernetes.ts:502]:
```suggestion
                        vscode.window.showInformationMessage("Successfully updated Project on OpenShift cluster");
```

**Review by freemanlatrell — CHANGES_REQUESTED** [review]

**Review by freemanlatrell — APPROVED** [review]
